project_id = "vklavozvzfqhxzoczqnp"

[functions.create-user]
verify_jwt = true

[functions.init-superadmin]
verify_jwt = false

[functions.init-admin]
verify_jwt = false

[functions.suggest-car-size]
verify_jwt = false

[functions.send-sms-code]
verify_jwt = false

[functions.verify-sms-code]
verify_jwt = false
