project_id = "vklavozvzfqhxzoczqnp"

[functions.create-user]
verify_jwt = true

[functions.init-superadmin]
verify_jwt = false

[functions.init-admin]
verify_jwt = false

[functions.suggest-car-size]
verify_jwt = false

[functions.send-sms-code]
verify_jwt = false

[functions.verify-sms-code]
verify_jwt = false

[functions.send-reminders]
verify_jwt = false

[functions.create-reservation-direct]
verify_jwt = false

[functions.send-sms-message]
verify_jwt = false

[functions.generate-offer-pdf]
verify_jwt = false

[functions.extract-price-list]
verify_jwt = false

[functions.parse-voice-reservation]
verify_jwt = false

[functions.manage-instance-users]
verify_jwt = false

[functions.reset-password]
verify_jwt = true

[functions.send-push-notification]
verify_jwt = false

[functions.get-manifest]
verify_jwt = false

[functions.get-public-config]
verify_jwt = false

[functions.send-offer-email]
verify_jwt = false

[functions.get-customer-info]
verify_jwt = false

[functions.test-sentry-error]
verify_jwt = false

[functions.send-offer-reminders]
verify_jwt = false

[functions.seed-e2e-reset]
verify_jwt = false

[functions.seed-e2e-scenario]
verify_jwt = false

[functions.get-embed-config]
verify_jwt = false

[functions.submit-lead]
verify_jwt = false
